[2023-09-18T16:53:38.070+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.spark_submit_task manual__2023-09-18T11:08:24.803736+00:00 [queued]>
[2023-09-18T16:53:38.075+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.spark_submit_task manual__2023-09-18T11:08:24.803736+00:00 [queued]>
[2023-09-18T16:53:38.075+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T16:53:38.085+0545] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-09-18 11:08:24.803736+00:00
[2023-09-18T16:53:38.089+0545] {standard_task_runner.py:57} INFO - Started process 141687 to run task
[2023-09-18T16:53:38.092+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'spark_submit_task', 'manual__2023-09-18T11:08:24.803736+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpcy52ggv6']
[2023-09-18T16:53:38.094+0545] {standard_task_runner.py:85} INFO - Job 84: Subtask spark_submit_task
[2023-09-18T16:53:38.131+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.spark_submit_task manual__2023-09-18T11:08:24.803736+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T16:53:38.175+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T11:08:24.803736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T11:08:24.803736+00:00'
[2023-09-18T16:53:38.179+0545] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-09-18T16:53:38.180+0545] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default  --function postgres_to_dataframe
[2023-09-18T16:53:39.451+0545] {spark_submit.py:491} INFO - 23/09/18 16:53:39 WARN Utils: Your hostname, ubuntu-Lenovo-Legion-5-15ARH05 resolves to a loopback address: 127.0.1.1; using 192.168.0.114 instead (on interface wlp4s0)
[2023-09-18T16:53:39.454+0545] {spark_submit.py:491} INFO - 23/09/18 16:53:39 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2023-09-18T16:53:39.513+0545] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-09-18T16:53:39.539+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default  --function postgres_to_dataframe. Error code is: 1.
[2023-09-18T16:53:39.541+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=spark_submit_task, execution_date=20230918T110824, start_date=20230918T110838, end_date=20230918T110839
[2023-09-18T16:53:39.549+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task spark_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default  --function postgres_to_dataframe. Error code is: 1.; 141687)
[2023-09-18T16:53:39.586+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T16:53:39.594+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
