[2023-09-18T13:43:34.271+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-18T07:58:25.183131+00:00 [queued]>
[2023-09-18T13:43:34.276+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-18T07:58:25.183131+00:00 [queued]>
[2023-09-18T13:43:34.276+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:43:34.287+0545] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): file_sensor_task> on 2023-09-18 07:58:25.183131+00:00
[2023-09-18T13:43:34.291+0545] {standard_task_runner.py:57} INFO - Started process 74435 to run task
[2023-09-18T13:43:34.294+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'file_sensor_task', 'manual__2023-09-18T07:58:25.183131+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmp1eizxzdp']
[2023-09-18T13:43:34.296+0545] {standard_task_runner.py:85} INFO - Job 18: Subtask file_sensor_task
[2023-09-18T13:43:34.331+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.file_sensor_task manual__2023-09-18T07:58:25.183131+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T13:43:34.387+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='file_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T07:58:25.183131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T07:58:25.183131+00:00'
[2023-09-18T13:43:34.391+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-18T13:43:34.391+0545] {filesystem.py:64} INFO - Poking for file /../Airflow_Assignments/*.csv
[2023-09-18T13:44:04.401+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-18T13:44:04.401+0545] {filesystem.py:64} INFO - Poking for file /../Airflow_Assignments/*.csv
[2023-09-18T13:44:34.424+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-18T13:44:34.424+0545] {filesystem.py:64} INFO - Poking for file /../Airflow_Assignments/*.csv
[2023-09-18T13:45:04.457+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-18T13:45:04.458+0545] {filesystem.py:64} INFO - Poking for file /../Airflow_Assignments/*.csv
[2023-09-18T13:45:34.467+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-18T13:45:34.468+0545] {filesystem.py:64} INFO - Poking for file /../Airflow_Assignments/*.csv
[2023-09-18T13:45:34.468+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.0800244889997 seconds exceeds the specified timeout of 120.0.
[2023-09-18T13:45:34.474+0545] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=project_dag, task_id=file_sensor_task, execution_date=20230918T075825, start_date=20230918T075834, end_date=20230918T080034
[2023-09-18T13:45:34.605+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task file_sensor_task (Sensor has timed out; run duration of 120.0800244889997 seconds exceeds the specified timeout of 120.0.; 74435)
[2023-09-18T13:45:34.633+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:45:34.661+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
