[2023-09-18T13:52:24.338+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:07:13.603447+00:00 [queued]>
[2023-09-18T13:52:24.345+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:07:13.603447+00:00 [queued]>
[2023-09-18T13:52:24.346+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:52:24.357+0545] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): load_to_postgres_task> on 2023-09-18 08:07:13.603447+00:00
[2023-09-18T13:52:24.360+0545] {standard_task_runner.py:57} INFO - Started process 77691 to run task
[2023-09-18T13:52:24.364+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'load_to_postgres_task', 'manual__2023-09-18T08:07:13.603447+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpjkjz1vhz']
[2023-09-18T13:52:24.366+0545] {standard_task_runner.py:85} INFO - Job 28: Subtask load_to_postgres_task
[2023-09-18T13:52:24.394+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:07:13.603447+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T13:52:24.441+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T08:07:13.603447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T08:07:13.603447+00:00'
[2023-09-18T13:52:24.442+0545] {sql.py:274} INFO - Executing: COPY user_input_table FROM '/home/ubuntu/airflow/Airflow_Assignments/user_data.csv' CSV HEADER;
[2023-09-18T13:52:24.445+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T13:52:24.487+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T13:52:24.488+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2023-09-18T13:52:24.493+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=load_to_***_task, execution_date=20230918T080713, start_date=20230918T080724, end_date=20230918T080724
[2023-09-18T13:52:24.502+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task load_to_***_task (could not translate host name "***" to address: Temporary failure in name resolution
; 77691)
[2023-09-18T13:52:24.534+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:52:24.542+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
