[2023-09-18T16:53:29.255+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T11:08:24.803736+00:00 [queued]>
[2023-09-18T16:53:29.259+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T11:08:24.803736+00:00 [queued]>
[2023-09-18T16:53:29.259+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T16:53:29.269+0545] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): load_to_postgres_task> on 2023-09-18 11:08:24.803736+00:00
[2023-09-18T16:53:29.273+0545] {standard_task_runner.py:57} INFO - Started process 141515 to run task
[2023-09-18T16:53:29.275+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'load_to_postgres_task', 'manual__2023-09-18T11:08:24.803736+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmp6xe1vzar']
[2023-09-18T16:53:29.277+0545] {standard_task_runner.py:85} INFO - Job 80: Subtask load_to_postgres_task
[2023-09-18T16:53:29.298+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T11:08:24.803736+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T16:53:29.335+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T11:08:24.803736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T11:08:24.803736+00:00'
[2023-09-18T16:53:29.336+0545] {sql.py:274} INFO - Executing: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;
[2023-09-18T16:53:29.339+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T16:53:29.418+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T16:53:29.434+0545] {sql.py:418} INFO - Running statement: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2023-09-18T16:53:29.440+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "user_input_table_pkey"
DETAIL:  Key (id)=(5171308) already exists.
CONTEXT:  COPY user_input_table, line 2

[2023-09-18T16:53:29.444+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=load_to_***_task, execution_date=20230918T110824, start_date=20230918T110829, end_date=20230918T110829
[2023-09-18T16:53:29.452+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task load_to_***_task (duplicate key value violates unique constraint "user_input_table_pkey"
DETAIL:  Key (id)=(5171308) already exists.
CONTEXT:  COPY user_input_table, line 2
; 141515)
[2023-09-18T16:53:29.487+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T16:53:29.495+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
