[2023-09-19T13:56:47.976+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:11:36.232606+00:00 [queued]>
[2023-09-19T13:56:47.980+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:11:36.232606+00:00 [queued]>
[2023-09-19T13:56:47.981+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:56:47.989+0545] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): file_sensor_task> on 2023-09-19 08:11:36.232606+00:00
[2023-09-19T13:56:47.993+0545] {standard_task_runner.py:57} INFO - Started process 24919 to run task
[2023-09-19T13:56:47.996+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'file_sensor_task', 'manual__2023-09-19T08:11:36.232606+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpppy5v2e2']
[2023-09-19T13:56:47.997+0545] {standard_task_runner.py:85} INFO - Job 96: Subtask file_sensor_task
[2023-09-19T13:56:48.017+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:11:36.232606+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-19T13:56:48.053+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='file_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T08:11:36.232606+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T08:11:36.232606+00:00'
[2023-09-19T13:56:48.057+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:56:48.057+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T13:57:18.091+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:57:18.091+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T13:57:48.123+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:57:48.123+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T13:57:48.124+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.06970979499965 seconds exceeds the specified timeout of 40.0.
[2023-09-19T13:57:48.131+0545] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=project_dag, task_id=file_sensor_task, execution_date=20230919T081136, start_date=20230919T081147, end_date=20230919T081248
[2023-09-19T13:57:48.145+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 96 for task file_sensor_task (Sensor has timed out; run duration of 60.06970979499965 seconds exceeds the specified timeout of 40.0.; 24919)
[2023-09-19T13:57:48.165+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T13:57:48.195+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
