[2023-09-18T15:52:27.535+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T10:07:16.323923+00:00 [queued]>
[2023-09-18T15:52:27.539+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T10:07:16.323923+00:00 [queued]>
[2023-09-18T15:52:27.540+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T15:52:27.549+0545] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): load_to_postgres_task> on 2023-09-18 10:07:16.323923+00:00
[2023-09-18T15:52:27.553+0545] {standard_task_runner.py:57} INFO - Started process 119167 to run task
[2023-09-18T15:52:27.556+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'load_to_postgres_task', 'manual__2023-09-18T10:07:16.323923+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpwsls6wos']
[2023-09-18T15:52:27.558+0545] {standard_task_runner.py:85} INFO - Job 68: Subtask load_to_postgres_task
[2023-09-18T15:52:27.594+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T10:07:16.323923+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T15:52:27.632+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T10:07:16.323923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T10:07:16.323923+00:00'
[2023-09-18T15:52:27.633+0545] {sql.py:274} INFO - Executing: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;
[2023-09-18T15:52:27.636+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T15:52:27.682+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T15:52:27.695+0545] {sql.py:418} INFO - Running statement: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2023-09-18T15:52:27.697+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "user_input_table_pkey"
DETAIL:  Key (id)=(5171308) already exists.
CONTEXT:  COPY user_input_table, line 2

[2023-09-18T15:52:27.701+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=load_to_***_task, execution_date=20230918T100716, start_date=20230918T100727, end_date=20230918T100727
[2023-09-18T15:52:27.709+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task load_to_***_task (duplicate key value violates unique constraint "user_input_table_pkey"
DETAIL:  Key (id)=(5171308) already exists.
CONTEXT:  COPY user_input_table, line 2
; 119167)
[2023-09-18T15:52:27.727+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T15:52:27.741+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
