[2023-09-18T13:51:22.775+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:06:11.720350+00:00 [queued]>
[2023-09-18T13:51:22.781+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:06:11.720350+00:00 [queued]>
[2023-09-18T13:51:22.781+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:22.793+0545] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): load_to_postgres_task> on 2023-09-18 08:06:11.720350+00:00
[2023-09-18T13:51:22.797+0545] {standard_task_runner.py:57} INFO - Started process 76933 to run task
[2023-09-18T13:51:22.799+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'load_to_postgres_task', 'manual__2023-09-18T08:06:11.720350+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpuoq5cwoz']
[2023-09-18T13:51:22.800+0545] {standard_task_runner.py:85} INFO - Job 23: Subtask load_to_postgres_task
[2023-09-18T13:51:22.821+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.load_to_postgres_task manual__2023-09-18T08:06:11.720350+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-18T13:51:22.859+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T08:06:11.720350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T08:06:11.720350+00:00'
[2023-09-18T13:51:22.861+0545] {sql.py:274} INFO - Executing: COPY user_input_table FROM '../Airflow_Assignments/user_data.csv' CSV HEADER;
[2023-09-18T13:51:22.864+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T13:51:22.958+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-18T13:51:22.960+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2023-09-18T13:51:22.966+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=load_to_***_task, execution_date=20230918T080611, start_date=20230918T080622, end_date=20230918T080622
[2023-09-18T13:51:22.982+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task load_to_***_task (could not translate host name "***" to address: Temporary failure in name resolution
; 76933)
[2023-09-18T13:51:23.011+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:51:23.019+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
